---
kind: pipeline
name: slack-wifi-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build_docker_image
    image: plugins/docker
    settings:
      repo: jeffreyvdb/slack_wifi
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest

---
kind: secret
name: docker_username
data: xP0n8GF9wLcNzfMNtOW2pdmDytlnJ0CJfIe3ukbMbkchUGGR3rg=

---
kind: secret
name: docker_password
data: G0yED+/5CGGbC+zGOtDW8ZRtveeBgjRWZcbC52dzv9I75O1hy6bS9goQJ01jt5th
