---
# TODO: Use build artificats instead of pipeline artifacts
# TODO: Use matrix for building
# TODO: Use built binary for testing or download newest go version on macos, linux, windows
trigger:
  - master

variables:
  GO_VERSION: 1.12.9

jobs:
  - job: run_unit_tests
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
        mac:
          imageName: "macos-10.14"
        windows:
          imageName: "windows-2019"

    pool:
      vmImage: $(imageName)

    steps:
      - script: |
          go version
          go test -v -cover ./...
        displayName: "Run tests"

  - job: build_linux_amd64

    pool:
      vmImage: "ubuntu-16.04"

    container: library/golang:$(GO_VERSION)

    dependsOn: run_unit_tests
    steps:
      - script: |
          GOOS=linux GOARCH=amd64 go build -tags netgo -ldflags '-w -extldflags "-static"' -o bin-linux-amd64 .
        displayName: "Build Linux go binary"

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/bin-linux-amd64
          artifact: slack-wifi-linux-amd64

  - job: build_windows_amd64

    pool:
      vmImage: "ubuntu-16.04"

    container: library/golang:$(GO_VERSION)

    dependsOn: run_unit_tests
    steps:
      - script: |
          GOOS=windows GOARCH=amd64 go build -tags netgo -ldflags '-w -extldflags "-static"' -o bin-windows-amd64 .
        displayName: "Build Windows go binary"

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/bin-windows-amd64
          artifact: slack-wifi-windows-amd64

  - job: build_macos_amd64

    pool:
      vmImage: "ubuntu-16.04"

    container: library/golang:$(GO_VERSION)

    dependsOn: run_unit_tests
    steps:
      - script: |
          GOOS=darwin GOARCH=amd64 go build -tags netgo -ldflags '-w -extldflags "-static"' -o bin-macos-amd64 .
        displayName: "Build MacOS go binary"

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/bin-macos-amd64
          artifact: slack-wifi-macos-amd64
