---
trigger:
  - master

jobs:
  - job: run_unit_tests
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - script: |
          go test ./...
        displayName: "Run tests"

  - job: build_linux_amd64
    pool:
      vmImage: "ubuntu-16.04"
    dependsOn: run_unit_tests
    steps:
      - script: |
          GOOS=linux GOARCH=amd64 go build -tags netgo -ldflags '-w -extldflags "-static"' -o bin-linux-amd64 .
        displayName: "Build Linux go binary"

  - job: build_macos_amd64
    pool:
      vmImage: "ubuntu-16.04"
    dependsOn: run_unit_tests
    steps:
      - script: |
          GOOS=darwin GOARCH=amd64 go build -tags netgo -ldflags '-w -extldflags "-static"' -o bin-macos-amd64 .
        displayName: "Build MacOS go binary"

  - job: publish_artifacts
    pool:
      vmImage: "ubuntu-16.04"
    dependsOn:
      - build_linux_amd64
      - build_macos_amd64
    steps:
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/bin-linux-amd64
          artifact: slack-wifi-linux-amd64

      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/bin-macos-amd64
          artifact: slack-wifi-macos-amd64
